### ISSUE TITLE
.deb package is built with expensive internal consistency checks

### ISSUE THREAD

**Issue by rbalint** [firebuild/firebuild#627]
Release builds are built with `-O3 -DNDEBUG`, but the Debian package is not, it is build with `-O2` and without passing `-DNDebug` enabling some more expensive checks, too.
Trivially passing -DNDEBUG via CPPFLAGS works on Ubuntu 20.04, but does not on Ubuntu 21.04, due to `lto-wrapper`:

```
/usr/lib/ccache/c++ -g -O2 -ffile-prefix-map=/home/rbalint/projects/build-area/firebuild-0.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++17 -W -Wall -Wextra -Werror -Wpointer-arith -Warray-bounds -Wcast-align -Wformat -Wformat-security -fstrict-overflow -Wstrict-overflow=4 -Wunreachable-code -Warray-bounds -fvisibility=hidden -Woverflow -Weffc++ -Wredundant-decls -Wno-format-zero-length -O2 -g -DNDEBUG -Wl,-Bsymbolic-functions -flto=auto -Wl,-z,relro CMakeFiles/fbb_test.dir/fbb_test.cc.o CMakeFiles/fbb_test.dir/fbbtest.cc.o -o fbb_test 
./obj-x86_64-linux-gnu/test/./fbbtest.h:130:16: error: type ‘struct _FBBTEST_Builder_testing’ violates the C++ One Definition Rule [-Werror=odr]
./obj-x86_64-linux-gnu/test/fbbtest.h:130:16: note: a different type is defined in another translation unit
./obj-x86_64-linux-gnu/test/./fbbtest.h:196:8: note: the first difference of corresponding definitions is field ‘has_reqint’
./obj-x86_64-linux-gnu/test/fbbtest.h:130:16: note: a type with different number of fields is defined in another translation unit
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[5]: *** [test/CMakeFiles/fbb_test.dir/build.make:134: test/fbb_test] Error 1
make[5]: Leaving directory '/home/rbalint/projects/build-area/firebuild-0.1/obj-x86_64-linux-gnu'
make[4]: *** [CMakeFiles/Makefile2:814: test/CMakeFiles/fbb_test.dir/all] Error 2
make[4]: Leaving directory '/home/rbalint/projects/build-area/firebuild-0.1/obj-x86_64-linux-gnu'
make[3]: *** [CMakeFiles/Makefile2:944: test/CMakeFiles/check.dir/rule] Error 2
make[3]: Leaving directory '/home/rbalint/projects/build-area/firebuild-0.1/obj-x86_64-linux-gnu'
make[2]: *** [Makefile:535: check] Error 2
make[2]: Leaving directory '/home/rbalint/projects/build-area/firebuild-0.1/obj-x86_64-linux-gnu'
make[1]: *** [debian/rules:23: override_dh_auto_test] Error 2
make[1]: Leaving directory '/home/rbalint/projects/build-area/firebuild-0.1'
make: *** [debian/rules:11: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

```

This needs a forward-proof solution.
